version: '3.8'

services:
  app:
    image: ghcr.io/i3ai3yi3ell/shorturl:latest
    container_name: shorturl_app
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - .env
    ports:
      - "127.0.0.1:9900:9000"
    volumes:
      - storage_data:/var/www/html/storage

volumes:
  storage_data:
